export const GROUP_BY_FILTER = 'Group By Filter';
export const DETAILS_DEFAULT_VIEW = 'Details ViewV2';
export const HISTORY_DEFAULT_VIEW = 'History ViewV2';
export const DEFAULT_VIEW_TYPE = 'View TypeV2';
export const DOCKED_VIEW = 'Docked';
export const FLYOUT_VIEW = 'Flyout';
export const CARD_VIEW = 'Card';
export const TABLE_VIEW = 'Table';
export const DEFAULT_TENANT = 'Default Tenant';
export const CONTINUE_TIMEOUT = 4000;
export const DATE_FORMAT_OPTION: any = { year: 'numeric', day: 'numeric', month: 'short' }; //// MMM DD,YYYY
export const DEFAULT_LOCALE = 'en-US';
