export enum SummaryTableFieldNames {
    ApprovalIdentifier = 'ApprovalIdentifier',
    SubmittedDate = 'SubmittedDate',
    Submitter = 'Submitter',
    UnitValue = 'UnitValue',
    CompanyCode = 'CompanyCode',
    IsRead = 'IsRead',
    viewDetails = 'viewDetails',
    actionDetails = 'actionDetails',
    submittedForFullName = 'submittedForFullName',
    assignmentName = 'assignmentName',
    laborDate = 'laborDate',
    laborHours = 'laborHours',
    laborCategoryName = 'laborCategoryName',
    submittedByFullName = 'submittedByFullName',
    isBillable = 'isBillable',
    laborNotes = 'laborNotes',
    Title = 'Title',
    CustomAttribute = 'CustomAttribute',
    allowInBulkApproval = 'allowInBulkApproval'
}
