// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace Microsoft.CFS.Approvals.SyntheticTransaction.Common;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

/// <summary>
/// Represents class to generate random data
/// </summary>
public static class RandomDataGenerator
{
    private static readonly Random random = new Random((int)DateTime.Now.Ticks);

    /// <summary>
    /// Generates random date
    /// </summary>
    /// <returns>Returns DateTime value</returns>
    public static DateTime RandomDay()
    {
        Random gen = new Random();
        int range = 1 * 365;
        return DateTime.Today.AddDays(-gen.Next(range));
    }

    /// <summary>
    /// Generates random numeric long value
    /// </summary>
    /// <param name="length">represents number of digit</param>
    /// <returns>returns random digit value</returns>
    public static string RandomDigits(int length)
    {
        var random = new Random();
        string s = string.Empty;
        for (int i = 0; i < length; i++)
            s = String.Concat(s, random.Next(10).ToString());
        return s;
    }

    /// <summary>
    /// Generates random character
    /// </summary>
    /// <returns>random char</returns>
    public static char RandomChar()
    {
        var random = new Random();
        char[] alphabates = { 'A', 'B', 'C' };
        int s = random.Next(0, 2);
        return alphabates[s];
    }

    /// <summary>
    /// Generates random boolean value
    /// </summary>
    /// <returns>Return Boolean</returns>
    public static bool RandomBoolean()
    {
        var random = new Random();
        int s = random.Next(0, 1);
        return s == 0 ? false : false;
    }

    /// <summary>
    /// Generates random integer value
    /// </summary>
    /// <returns>returns integer</returns>
    public static string RandomInteger()
    {
        var random = new Random();

        return random.Next(1, 25000).ToString();
    }

    /// <summary>
    /// Generate decimal value
    /// </summary>
    /// <param name="length">number of digits</param>
    /// <param name="decimalPoint">represent decimal point value</param>
    /// <returns>Returns decimal value</returns>
    public static string DecimalDigits(int length, int decimalPoint)
    {
        var random = new Random();
        string decimalNumber = string.Empty;
        for (int i = 1; i <= length; i++)
        {
            decimalNumber = String.Concat(decimalNumber, random.Next(10).ToString());
            decimalNumber = i == decimalPoint ? String.Concat(decimalNumber, ".") : decimalNumber;
        }
        return decimalNumber;
    }

    /// <summary>
    /// Generate random word(s) based on word count
    /// </summary>
    /// <param name="wordCount">Number of words to be returned</param>
    /// <param name="capitalize">Repesent if word is needed to be in capital</param>
    /// <returns>Returns random word(s)</returns>
    public static IEnumerable<string> Words(int wordCount = 4, bool capitalize = false)
    {
        var words = Common.Words.Common.Random(wordCount);
        if (capitalize)
        {
            words = words.Select(w => CultureInfo.CurrentCulture.TextInfo.ToTitleCase(w));
        }
        return words;
    }

    /// <summary>
    /// Generic method to generate random data
    /// </summary>
    /// <typeparam name="T">Type to be generated</typeparam>
    /// <param name="source">IEnumerable<T></param>
    /// <param name="numberOfItems">Number of items</param>
    /// <returns>Returns list of item based on type T</returns>
    public static IEnumerable<T> Random<T>(this IEnumerable<T> source, int numberOfItems)
    {
        var lastItemIndex = source.Count() - 1;
        return Enumerable.Range(1, numberOfItems)
                         .Select(_ => source.ElementAt(Int(min: 0, max: lastItemIndex)));
    }

    public static int Int(int min = int.MinValue, int max = int.MaxValue)
    {
        var val = random.Next(min, max >= int.MaxValue ? int.MaxValue : max + 1);
        return val;
    }
}

/// <summary>
/// Class representing word dictionary
/// </summary>
public static class Words
{
    #region Common

    /// <summary>
    /// Represent array of random workds
    /// </summary>
    public static readonly string[] Common = new[]
    {
            "ability",
            "able",
            "about",
            "above",
            "accept",
            "according",
            "across",
            "act",
            "action",
            "activity",
            "actually",
            "add",
            "address",
            "administration",
            "adult",
            "affect",
            "after",
            "again",
            "against",
            "age",
            "agency",
            "agent",
            "ago",
            "agree",
            "ahead",
            "air",
            "all",
            "allow",
            "almost",
            "along",
            "already",
            "also",
            "although",
            "always",
            "American",
            "among",
            "amount",
            "analysis",
            "anger",
            "animal",
            "another",
            "answer",
            "any",
            "anyone",
            "anything",
            "appear",
            "apply",
            "approach",
            "area",
            "argue",
            "arm",
            "around",
            "arrive",
            "art",
            "article",
            "artist",
            "as",
            "ask",
            "asparagus",
            "attack",
            "attention",
            "author",
            "authority",
            "available",
            "avocado",
            "avoid",
            "away",
            "baby",
            "back",
            "bad",
            "bag",
            "ball",
            "bank",
            "bar",
            "base",
            "bean",
            "beast",
            "beat",
            "beautiful",
            "because",
            "become",
            "bed",
            "before",
            "before",
            "begin",
            "behavior",
            "behind",
            "believe",
            "benefit",
            "best",
            "better",
            "between",
            "beyond",
            "big",
            "bill",
            "billion",
            "bird",
            "bit",
            "black",
            "blood",
            "blue",
            "board",
            "body",
            "bond",
            "book",
            "both",
            "box",
            "boy",
            "break",
            "bring",
            "broccoli",
            "broth",
            "brother",
            "build",
            "building",
            "business",
            "butter",
            "buy",
            "call",
            "camera",
            "campaign",
            "cancer",
            "candidate",
            "car",
            "card",
            "care",
            "care",
            "career",
            "carry",
            "case",
            "catch",
            "cause",
            "cell",
            "center",
            "central",
            "century",
            "certain",
            "certainly",
            "chair",
            "challenge",
            "chance",
            "change",
            "character",
            "charge",
            "check",
            "cheese",
            "chicken",
            "child",
            "choice",
            "choose",
            "church",
            "chutney",
            "city",
            "claim",
            "clam",
            "class",
            "clear",
            "clearly",
            "close",
            "coach",
            "coffee",
            "cold",
            "collection",
            "college",
            "color",
            "come",
            "commercial",
            "common",
            "community",
            "company",
            "compare",
            "computer",
            "concern",
            "concussion",
            "condition",
            "conference",
            "Congress",
            "consider",
            "contain",
            "continue",
            "contraption",
            "control",
            "cost",
            "could",
            "country",
            "couple",
            "courage",
            "course",
            "court",
            "cousin",
            "cover",
            "crab",
            "create",
            "crime",
            "croissant",
            "cultural",
            "culture",
            "cup",
            "current",
            "cut",
            "dark",
            "data",
            "daughter",
            "day",
            "dead",
            "deal",
            "deal",
            "death",
            "decade",
            "decide",
            "decision",
            "deep",
            "defense",
            "degree",
            "Democrat",
            "democratic",
            "describe",
            "design",
            "design",
            "despite",
            "detail",
            "determine",
            "develop",
            "development",
            "die",
            "difference",
            "different",
            "difficult",
            "direction",
            "director",
            "discover",
            "discuss",
            "discussion",
            "disease",
            "doctor",
            "dog",
            "door",
            "down",
            "down",
            "draw",
            "dream",
            "drive",
            "drop",
            "drug",
            "duck",
            "during",
            "each",
            "each",
            "early",
            "early",
            "east",
            "easy",
            "eat",
            "economic",
            "economy",
            "edge",
            "education",
            "effect",
            "effort",
            "eight",
            "either",
            "election",
            "else",
            "employee",
            "end",
            "energy",
            "enjoy",
            "enough",
            "enter",
            "entire",
            "environment",
            "especially",
            "establish",
            "even",
            "evening",
            "event",
            "ever",
            "every",
            "everybody",
            "everyone",
            "everything",
            "evidence",
            "exactly",
            "example",
            "executive",
            "exist",
            "expect",
            "experience",
            "expert",
            "explain",
            "eye",
            "face",
            "face",
            "fact",
            "factor",
            "fail",
            "fall",
            "fallacy",
            "family",
            "far",
            "farm",
            "father",
            "fear",
            "federal",
            "feel",
            "feeling",
            "few",
            "field",
            "fight",
            "figure",
            "fill",
            "film",
            "final",
            "finally",
            "financial",
            "find",
            "fine",
            "finger",
            "finish",
            "fire",
            "firm",
            "first",
            "fish",
            "five",
            "floor",
            "fly",
            "focus",
            "follow",
            "food",
            "foot",
            "force",
            "foreign",
            "forget",
            "form",
            "form",
            "former",
            "forward",
            "four",
            "free",
            "friend",
            "full",
            "fund",
            "future",
            "game",
            "garden",
            "gas",
            "general",
            "generation",
            "girl",
            "give",
            "glass",
            "gluttony",
            "goal",
            "good",
            "government",
            "grammar",
            "great",
            "green",
            "ground",
            "group",
            "grow",
            "growth",
            "guess",
            "guitar",
            "gun",
            "guy",
            "hair",
            "half",
            "hammer",
            "hand",
            "hang",
            "happen",
            "happy",
            "hard",
            "hard",
            "harm",
            "head",
            "health",
            "hear",
            "heart",
            "heat",
            "heavy",
            "help",
            "her",
            "here",
            "herself",
            "high",
            "him",
            "himself",
            "history",
            "hit",
            "hold",
            "home",
            "hope",
            "horse",
            "hospital",
            "hot",
            "hotel",
            "hour",
            "house",
            "how",
            "however",
            "huge",
            "human",
            "hundred",
            "husband",
            "idea",
            "identify",
            "image",
            "imagine",
            "impact",
            "important",
            "improve",
            "in",
            "include",
            "including",
            "increase",
            "indeed",
            "indicate",
            "individual",
            "indivisible",
            "industry",
            "information",
            "inside",
            "instead",
            "institution",
            "interest",
            "international",
            "interview",
            "into",
            "investment",
            "involve",
            "issue",
            "item",
            "its",
            "itself",
            "jam",
            "jelly",
            "job",
            "join",
            "junk",
            "junket",
            "jury",
            "just",
            "justice",
            "kale",
            "keep",
            "kelp",
            "ketchup",
            "kid",
            "kill",
            "kind",
            "knowledge",
            "land",
            "language",
            "large",
            "last",
            "late",
            "later",
            "laugh",
            "law",
            "lawyer",
            "lay",
            "lead",
            "leader",
            "learn",
            "least",
            "leave",
            "left",
            "leg",
            "legal",
            "less",
            "less",
            "let",
            "letter",
            "lettuce",
            "level",
            "lie",
            "life",
            "light",
            "like",
            "like",
            "likely",
            "line",
            "list",
            "listen",
            "litter",
            "little",
            "live",
            "lizard",
            "lobster",
            "local",
            "long",
            "look",
            "loop",
            "lose",
            "loss",
            "lot",
            "love",
            "low",
            "lozenge",
            "luck",
            "lunch",
            "machine",
            "macho",
            "magazine",
            "main",
            "maintain",
            "major",
            "man",
            "manage",
            "management",
            "manager",
            "many",
            "market",
            "marriage",
            "material",
            "matter",
            "may",
            "maybe",
            "me",
            "mean",
            "measure",
            "media",
            "medical",
            "meet",
            "meeting",
            "member",
            "memory",
            "mention",
            "message",
            "method",
            "middle",
            "might",
            "military",
            "million",
            "mind",
            "minute",
            "miss",
            "mittens",
            "model",
            "modern",
            "moment",
            "money",
            "month",
            "more",
            "morning",
            "most",
            "mother",
            "move",
            "movement",
            "movie",
            "much",
            "muck",
            "muffin",
            "music",
            "must",
            "mustard",
            "myself",
            "name",
            "name",
            "nation",
            "national",
            "natural",
            "nature",
            "near",
            "nearly",
            "necessary",
            "need",
            "need",
            "network",
            "never",
            "new",
            "news",
            "next",
            "nice",
            "night",
            "no",
            "none",
            "nope",
            "north",
            "note",
            "note",
            "nothing",
            "notice",
            "now",
            "number",
            "occur",
            "off",
            "offend",
            "offer",
            "office",
            "officer",
            "official",
            "often",
            "oh",
            "oil",
            "ok",
            "old",
            "on",
            "once",
            "one",
            "only",
            "onto",
            "open",
            "open",
            "operation",
            "opportunity",
            "order",
            "organization",
            "other",
            "otter",
            "our",
            "out",
            "out",
            "outside",
            "over",
            "over",
            "own",
            "owner",
            "page",
            "pain",
            "paper",
            "parent",
            "parsley",
            "part",
            "particular",
            "party",
            "pass",
            "past",
            "paste",
            "pastime",
            "patient",
            "pattern",
            "paws",
            "pay",
            "peace",
            "people",
            "per",
            "perform",
            "performance",
            "perhaps",
            "period",
            "person",
            "personal",
            "phone",
            "physical",
            "pick",
            "pickle",
            "picture",
            "piece",
            "placard",
            "place",
            "plan",
            "planet",
            "plant",
            "play",
            "play",
            "player",
            "pluck",
            "PM",
            "point",
            "poker",
            "police",
            "policy",
            "political",
            "politics",
            "poor",
            "popular",
            "population",
            "pork",
            "position",
            "possible",
            "power",
            "practice",
            "pram",
            "prepare",
            "present",
            "president",
            "pressure",
            "pretty",
            "price",
            "pride",
            "private",
            "probably",
            "problem",
            "process",
            "produce",
            "product",
            "production",
            "professor",
            "program",
            "project",
            "property",
            "protect",
            "prove",
            "provide",
            "public",
            "publicity",
            "puffin",
            "pull",
            "purpose",
            "push",
            "put",
            "quahog",
            "quality",
            "question",
            "quickly",
            "quite",
            "race",
            "radio",
            "radish",
            "raise",
            "range",
            "ratchet",
            "rate",
            "rather",
            "reach",
            "read",
            "ready",
            "real",
            "reality",
            "realize",
            "really",
            "reason",
            "receive",
            "recent",
            "recently",
            "recognize",
            "record",
            "red",
            "reduce",
            "reflect",
            "region",
            "relationship",
            "religious",
            "relish",
            "remain",
            "remember",
            "remove",
            "report",
            "represent",
            "Republican",
            "require",
            "research",
            "resource",
            "respond",
            "response",
            "rest",
            "result",
            "return",
            "reveal",
            "right",
            "rise",
            "risk",
            "road",
            "robot",
            "rock",
            "role",
            "room",
            "rule",
            "run",
            "salsa",
            "same",
            "sand",
            "save",
            "scallop",
            "scene",
            "school",
            "science",
            "scone",
            "sea",
            "season",
            "seat",
            "second",
            "section",
            "secular",
            "security",
            "see",
            "seek",
            "seem",
            "sell",
            "send",
            "sense",
            "series",
            "serious",
            "serve",
            "service",
            "set",
            "set",
            "seven",
            "several",
            "shake",
            "shampoo",
            "share",
            "shark",
            "sheep",
            "shoot",
            "short",
            "shortage",
            "should",
            "shoulder",
            "shovel",
            "show",
            "shrimp",
            "side",
            "sign",
            "significant",
            "similar",
            "simple",
            "simply",
            "since",
            "since",
            "sing",
            "single",
            "sister",
            "sit",
            "site",
            "situation",
            "six",
            "size",
            "skill",
            "skin",
            "small",
            "snowflake",
            "so",
            "soap",
            "social",
            "society",
            "soldier",
            "some",
            "somebody",
            "someone",
            "something",
            "sometimes",
            "son",
            "song",
            "soon",
            "sort",
            "sound",
            "source",
            "south",
            "space",
            "speak",
            "special",
            "specific",
            "spend",
            "sponge",
            "sport",
            "spring",
            "staff",
            "stage",
            "stand",
            "standard",
            "star",
            "start",
            "state",
            "state",
            "statement",
            "station",
            "stay",
            "steam",
            "step",
            "still",
            "stock",
            "stop",
            "store",
            "stork",
            "storm",
            "story",
            "strategy",
            "street",
            "strong",
            "structure",
            "student",
            "study",
            "study",
            "stuff",
            "style",
            "subject",
            "success",
            "such",
            "suction",
            "suddenly",
            "suggest",
            "summer",
            "supper",
            "support",
            "sure",
            "surf",
            "surface",
            "system",
            "table",
            "take",
            "talk",
            "tank",
            "task",
            "tax",
            "teach",
            "teacher",
            "team",
            "technology",
            "television",
            "tell",
            "ten",
            "tend",
            "tenderloin",
            "term",
            "test",
            "test",
            "than",
            "thank",
            "that",
            "them",
            "themselves",
            "then",
            "theory",
            "there",
            "these",
            "thing",
            "think",
            "third",
            "those",
            "though",
            "thought",
            "thousand",
            "three",
            "through",
            "throughout",
            "throw",
            "thus",
            "time",
            "today",
            "together",
            "tonight",
            "too",
            "top",
            "topiary",
            "total",
            "tough",
            "toward",
            "town",
            "trade",
            "traditional",
            "training",
            "trap",
            "treat",
            "treatment",
            "tree",
            "trial",
            "trip",
            "trouble",
            "true",
            "truth",
            "try",
            "turn",
            "TV",
            "two",
            "type",
            "under",
            "understand",
            "unit",
            "until",
            "up",
            "upon",
            "us",
            "use",
            "usually",
            "value",
            "vampire",
            "various",
            "very",
            "view",
            "violence",
            "visit",
            "voice",
            "waffle",
            "wait",
            "walk",
            "wall",
            "wallaby",
            "want",
            "war",
            "watch",
            "water",
            "way",
            "weapon",
            "wear",
            "week",
            "weight",
            "well",
            "well",
            "west",
            "whale",
            "whatever",
            "when",
            "when",
            "where",
            "whether",
            "which",
            "while",
            "white",
            "whole",
            "whom",
            "whose",
            "why",
            "wide",
            "wife",
            "win",
            "window",
            "within",
            "without",
            "wolf",
            "woman",
            "wonder",
            "word",
            "work",
            "worker",
            "world",
            "worry",
            "wrench",
            "write",
            "writer",
            "wrong",
            "yard",
            "yeah",
            "year",
            "yes",
            "yet",
            "yeti",
            "young",
            "your",
            "yourself",
            "zebra",
            "zombie",
        };

    #endregion Common
}